---
repos:
- repo: local
  hooks:
  - id: sops-encrypted
    name: Ensure *.enc.* files are SOPS-encrypted
    language: system
    # TODO: `just check` covers the whole files, not only committed ones.
    pass_filenames: false
    files: "\\.enc\\.(ya?ml|json|env|md)$"
    entry: just check
- repo: https://github.com/editorconfig-checker/editorconfig-checker.python
  rev: "3.6.1"
  hooks:
  - id: editorconfig-checker
    args:
    - --exclude=LICENSE
# https://github.com/google/yamlfmt/blob/main/docs/pre-commit.md
- repo: https://github.com/google/yamlfmt.git
  rev: v0.21.0
  hooks:
  - id: yamlfmt
    # In pre-commit we run yamlfmt in "lint" mode.
    # If you want to format the files, run `yamlfmt .` manually.
    args:
    - -lint
    - -quiet
    - -conf=./.yamlfmt
