---
creation_rules:
# Any *.enc.{yaml,json,env,md} file, anywhere in the repo,
- path_regex: \.enc\.(ya?ml|json|env|md|tfvars)$
  age: >-
    age1yltgwsnfxgstlyhf2ek9kcug0f6hw9dkhkang9kcdr77qgj8ay4qg6p3yy,
    age1983r92uvhyfsud6nvn5pjnv7jvkxx3wsfhu68j32ll8uqpnwmass90k80w
