---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: nvidia
  # TODO: This is enforced by the namespace defined in kustomization.yaml. Better find a way to create this in flux-system namespace.
  namespace: gpu-operator
spec:
  # how often source-controller re-fetches the chart index from NVIDIA's repo
  interval: 24h
  url: https://helm.ngc.nvidia.com/nvidia
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: gpu-operator
  namespace: gpu-operator
spec:
  interval: 15m
  chart:
    spec:
      chart: gpu-operator
      version: "v26.3.2"
      sourceRef:
        kind: HelmRepository
        name: nvidia
        namespace: gpu-operator
  # values:
  #   driver:
  #     enabled: false
  #   toolkit:
  #     enabled: false
  valuesFrom:
  - kind: ConfigMap
    name: gpu-operator-config
    valuesKey: config.yaml
---
# https://github.com/NVIDIA/gpu-usage-monitor/tree/main
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: gpu-usage-monitor
  # TODO: This is enforced by the namespace defined in kustomization.yaml. Better find a way to create this in flux-system namespace.
  namespace: gpu-operator
spec:
  type: oci
  interval: 24h
  url: oci://ghcr.io/nvidia/gpu-usage-monitor
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: gpu-usage-monitor
  namespace: gpu-operator
spec:
  interval: 15m
  chart:
    spec:
      # helm show chart oci://ghcr.io/nvidia/gpu-usage-monitor/gpu-usage-monitor
      chart: gpu-usage-monitor
      version: "1.0.0"
      sourceRef:
        kind: HelmRepository
        name: gpu-usage-monitor
        namespace: gpu-operator
  values:
    # Deploy only the dashboard
    prometheus:
      enabled: false
    grafana:
      enabled: false
