---
# This config is used to generate a config map with the GPU operator values
namespace: gpu-operator
generatorOptions:
  # Have consistent name for valuesFrom to reference
  disableNameSuffixHash: true
configMapGenerator:
- name: gpu-operator-config
  files:
  - config.yaml
resources:
- deploy.yaml
- grafana-dashboards.yaml
