---
# This config is used to generate a config map with the GPU operator values
generatorOptions:
  # Have consistent name for valuesFrom to reference
  disableNameSuffixHash: true
configMapGenerator:
- name: gpu-operator-values
  files:
  - config.yaml
resources:
- deploy.yaml
