---
# https://docs.vllm.ai/en/stable/deployment/k8s/
# https://docs.vllm.ai/en/stable/deployment/integrations/production-stack/
# https://github.com/vllm-project/production-stack/tree/main/helm
# https://docs.vllm.ai/projects/production-stack/en/latest/index.html
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: vllm-stack
  namespace: flux-system
spec:
  interval: 1h
  url: https://vllm-project.github.io/production-stack
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: vllm-stack
  namespace: vllm-stack
spec:
  interval: 15m
  # timeout: 15m
  chart:
    spec:
      chart: vllm-stack
      version: "0.1.11"
      sourceRef:
        kind: HelmRepository
        name: vllm-stack
        namespace: vllm-stack
  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  # https://docs.vllm.ai/en/stable/deployment/integrations/production-stack/
  # https://github.com/vllm-project/production-stack/blob/vllm-stack-0.1.11/helm/values.yaml
  # https://docs.vllm.ai/projects/production-stack/en/latest/getting_started/quickstart.html
  # https://github.com/vllm-project/production-stack/blob/main/tutorials/assets/values-01-minimal-example.yaml
  values:
    grafanaDashboards:
      # https://github.com/vllm-project/production-stack/tree/main/helm/dashboards
      # See grafana-dashboard.yaml
      enabled: false
    routerSpec:
      serviceMonitor:
        enabled: true
    servingEngineSpec:
      serviceMonitor:
        enabled: true
      # We have 1 GPU
      strategy:
        type: Recreate
      runtimeClassName: "nvidia"
      # https://docs.vllm.ai/en/stable/models/supported_models/
      modelSpec:
      # - name: "opt125m"
      #   repository: "vllm/vllm-openai"
      #   # vLLM engine version
      #   tag: "v0.23.0"
      #   modelURL: "facebook/opt-125m"
      #   replicaCount: 1
      #   requestCPU: 6
      #   requestMemory: "16Gi"
      #   requestGPU: 1
      #   # Optional resource limits - if not specified, only GPU will have a limit
      #   # limitCPU: "8"
      #   # limitMemory: "32Gi"
      #   # NOT mig. Our card has no MIG
      #   requestGPUType: "nvidia.com/gpu"
      #   storageClass: "local-path"
      #
      # https://docs.vllm.ai/projects/recipes/en/latest/OpenAI/GPT-OSS.html
      # https://docs.vllm.ai/projects/ascend/en/latest/tutorials/models/gpt-oss-120b.html
      - name: "gptoss20b"
        repository: "vllm/vllm-openai"
        # vLLM engine version
        tag: "v0.24.0"
        modelURL: "openai/gpt-oss-20b"
        replicaCount: 1
        requestCPU: 6
        requestMemory: "16Gi"
        requestGPU: 1
        # Optional resource limits - if not specified, only GPU will have a limit
        # limitCPU: "8"
        # limitMemory: "32Gi"
        # NOT mig. Our card has no MIG
        requestGPUType: "nvidia.com/gpu"
        storageClass: "local-path"
        pvcStorage: "60Gi"
        hf_token:
          secretName: "hf-token"
          secretKey: "token"
        vllmConfig:
          # Error:
          # > (EngineCore pid=239) ValueError: To serve at least one request with the model's max seq len (131072),
          # > (3.05 GiB KV cache is needed, which is larger than the available KV cache memory (2.62 GiB).
          # > Based on the available memory, the estimated maximum model length is 112208.
          # > Try increasing `gpu_memory_utilization` (which also controls CPU memory on the CPU backend) or
          # > decreasing `max_model_len` when initializing the engine.
          # > See https://docs.vllm.ai/en/latest/configuration/conserving_memory/ for more details.
          #
          # --max-model-len represents the context length, which is the maximum value of the input plus output for a single request.
          # vLLM pre-reserves KV cache for the full context at startup.
          # > (APIServer pid=1) INFO 06-18 11:27:23 [model.py:1745] Using max model len 131072
          maxModelLen: 65536 # 131072/2=65536 tokens (64K context)
          # --gpu-memory-utilization represents the proportion of HBM that vLLM will use for actual inference.
          # Its essential function is to calculate the available kv_cache size.
          # > (EngineCore pid=239) INFO 06-18 11:31:55 [gpu_model_runner.py:5187] Model loading took 13.8 GiB memory and 117.712730 seconds
          # Model weights is ~13.8 GiB, whatever's left is KV cache.
          gpuMemoryUtilization: 0.92
          #
          # budget = 20GB * 0.92 ≈ 18.4 GiB
          # KV pool = budget − weights − CUDA graphs − activations/overhead ≈ 2.62 GiB
          #         ≈ 18.4   − 13.8    − 0.39        − ~1.6
          extraArgs:
          - "--served-model-name"
          - "gpt-oss-20b"
          # Enable support for calling user-defined functions
          # https://docs.vllm.ai/projects/recipes/en/latest/OpenAI/GPT-OSS.html#function-calling
          - "--tool-call-parser"
          - "openai" # gpt-oss speaks the OpenAI harmony format, so use the "openai" parser
          - "--enable-auto-tool-choice"
