apiVersion: v1
stringData:
    #ENC[AES256_GCM,data:K1/V+gLLLoPdHiyCWoFkYLUuJuFPxlY3X69tSRunx9fPIn8SyGz1RDb+Bme3cldrHTfv9j4=,iv:9OepStjNk4HsrI5rJfZwY4U/hcJRcZPAwbZbpXdg9u0=,tag:BMJi6D6Yi/oxm60evsxKxQ==,type:comment]
    token: ENC[AES256_GCM,data:+1KNWStJEPtwPzy1M83az788QGcKU5f2IeKSEqlnNDGvHnas9w==,iv:cEkg8LpKnhGP14UZpFH6QLbkLRdCmJzwYwKpFz0rv2E=,tag:r66ATuc7YZaPAogwGm/zcw==,type:str]
kind: Secret
metadata:
    name: hf-token
    namespace: vllm-stack
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqcXFVMHVwOS9RdGx3QnRj
            M0h0M2NjTVlwWHFJRzJRck9RVDFNTmhsNXdBCkJSSlBzeDYzR2tFWFFMOUw1dWdv
            eWxDeDNQL0lrV0hObDNrTUVlcTRGT2MKLS0tIFBtKzhpb2RCSzZ2c2tTQmVQSEdS
            M0g1Vk9YWUtaeWp6Sjg4OU5xTCtQaU0KMcjqA8/bLIrukD8wz+NBArhf5r56XgsB
            rxDBfUIgFIwfBivJiJtP1O9lbnFfZBbjBGgsgVI2UnFnYuhnwbIPrg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1yltgwsnfxgstlyhf2ek9kcug0f6hw9dkhkang9kcdr77qgj8ay4qg6p3yy
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBvakovalJocUFjWHRCVUox
            aXd5cTkvaktiYTZ0OFBJblNmZ1dHRTVGYmtvCllQSFJKRVlkWHRtWjFYRTh4aVRo
            eEZWcjNONWFtcEtXV09ka0xqUWxrNWMKLS0tIFd5bERkdnd6WXF2b0w3SG8wWmdN
            Q2NIeEw0TFNqUTBKK3JPSDVYcmE1Y2sKiGTMoDl4+sE+JWqvcrhqHKiYjafCeNnR
            gPmGlCQ7xW99uD6Vl/TQy9adoNGpt9LuqCEvA3XNRbTZ5FOCyK9QEg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1983r92uvhyfsud6nvn5pjnv7jvkxx3wsfhu68j32ll8uqpnwmass90k80w
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-30T09:51:32Z"
    mac: ENC[AES256_GCM,data:oMbDnflc72oUrQ6JjDU1kHBEVdz4BLQiVj8GenKF4RRl33Mlz5EC1+Jxpwa85dNmH/xcvkk0RcdgwpZSzcIBaruMDBndxN5M2sCDw9CK/1mCCzir6kCTY+ks7NEdnR0XJZhl9S1vCKm9KTwBMf6tfimHK4d2Jd0ed1ZNXpH+UdI=,iv:dCIHxiUImOWvdrNQbo6Vnm/e/4DFvvmsqaEQPo7gIjI=,tag:H1/pfs6Mzl+feyMv/COF1w==,type:str]
    version: 3.13.1
