apiVersion: v1
stringData:
    #ENC[AES256_GCM,data:LP2tbEt6IkOWQ5R+5e17D/eyE9KSXytNOPtujyGNEH0b0KYJsehx/IZm1fxYyinNpznp7QU=,iv:9cROrtwBOHv8Y0QF3ojxVl2RfSbDji43AtGc6robirE=,tag:Udg8kmi1OHymBtI54vM42g==,type:comment]
    token: ENC[AES256_GCM,data:7n3ovLGewK8+8ux6ad7IiPbHfg9t2Wx+P8zYz851xR9UKY7EbQ==,iv:hwKcO+ZbfAlyamkV+eT5/uwhUcR5CURNqM4bAY4krH0=,tag:fLfaFf2JLjdUWP9ZiQkaTg==,type:str]
kind: Secret
metadata:
    name: hf-token
    namespace: vllm-stack
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAvZlJOaHhBbDZiWitCQzhG
            K0h6QlRGWlJGcTJnMjd6TFhIbEplaUNrQXpFCmxqU2JodDlBUlRuYUpxMTZnbjd5
            WDRGWTRnV2Q1ZGZVakNHWWwvelV3dmcKLS0tIHBkcjY4SXRSQ1pzQUVHMjdEQnJG
            UmFKc2ZlWnM2NjBtSlgwOTRyTnBtTzAKgdcUJvGA2mUKNL5JyK+f4KR0pqNSUDeI
            Vlg17z+VuS+AQsoOW+aePxb66hkFMY36zAOFT8iD57fuxB5E5UFtwg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1yltgwsnfxgstlyhf2ek9kcug0f6hw9dkhkang9kcdr77qgj8ay4qg6p3yy
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA2NU5JRmRyeUxQZkphaFln
            cXZqa0VHdUFna0NydWd4QUd3d1NKaWFqb1NRCk1MdlNXN1lza3ZkWWZRdGp2cXBD
            dFRWVGpDTFhtcldRb0JhVkpPLyt6bTgKLS0tIHZGc0paaXRPa3F0cXd2Y3BZdVpF
            RUFuajFKQWQ0NDhBM2NsdWhhcW9JaTgKOF9qRKODSUpCgekrRUsCGpjzv6+91ZKC
            neqriXzm6qm/wmJ37RG6DOiWMZjJ2HbS0h3hU1/87eDSo0SnwhCB7w==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1983r92uvhyfsud6nvn5pjnv7jvkxx3wsfhu68j32ll8uqpnwmass90k80w
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-06T14:46:44Z"
    mac: ENC[AES256_GCM,data:f4uYu2DfSr439PSpUDoPULhQtAfSlQJDjCH2rqWeKZS3ivx8KU/RMRS3LVvCRATdRKrO0df5uWEj8RQUy7xn3QB/7IqNZmTXjFb4hli4J8fS2EDl3bIhXJ306cB/JVHXkJmooCRi1CdE6zvicVPAVoPZDnfiacLPjUKByv4WfDw=,iv:wNG8zb0Wud3jtFYbQJk16cO4vdlNMkGxPS6PmavmAXk=,tag:UrwHt7IBaqYrd4ZzIkobnA==,type:str]
    version: 3.13.1
