apiVersion: v1
kind: Secret
metadata:
    name: litellm-values
    namespace: litellm
stringData:
    values.yaml: ENC[AES256_GCM,data:3HwU0WXCsEyvecjDLJUeRk59Z4ShYs7n8OMnkf3OaxkwJFqlEvtsd8Hrn/0zDK/AbDFeJm4cw4OypvVR2qw3MWzUojWe2GkZbC1i2Pe6K5h21NlB+0KDkF0OAykzopKIXOPeL0PAEq6CuGmQ0Sz2AzHWLUwgqKjL8PO80HiC9ko+mfZxHzVUdQC2fSG72PNwGLxF7EEwRoU40RrXlaGxefj4XXuAcELB44WA9d2KFF96GCYWP8avYqR21jhCOKWdLYo2YvMNFP/zQgTi29fX96oJpkn4POk1a3j3KU9YoQCrJj8NtHFeiMvKwFQ30jy2qWC4AK1dbhGiVe+2/QC6B3jbhOSW+0aFAmkOKylX94zFoqYfBD+havJxc1CdDtuVwqvlfp96WFAPYGMp73u3zlOZbQexAzDJufZzA8EjV6CR1uIEUcldmTATWATtHZhlAC4lBV3avjVofIHqFBcSmcp0EupB7lV19R4dd5XIlIh0rWih7q4nBXR8k7piuJmuKdp1g2gLkDF2lDtSHupxsZkC5ARqiTOr4zJwO+6Kz4Rwve7Nt3CyZkLgOkIULRDs2+j1BqwaziDBJrZbvYRI2tv8h+eYO4NiHZlWzmUrA1UGJCZNNzRgERDh1vMsp27UGMMNatDBlPCQDELdRJgArnp7BF/RWT6uhtDP6AE=,iv:CoBr7KHd6aX+/R6I9h69FQHBOYmX5LmaoCev6RkXRgw=,tag:/rFWrDE0JELbhB0Zc+Sbag==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmYzIwMmdjUlBUNXZ4eUI5
            NE5tRDR4WGN3aHRrcDNPSHdBTlVnVEFtblg0CkhPR29qR1dHOWhsQkNEMEpZeGt4
            MFRiSXRFanE1OXFtN2dlOW15SGZnZkUKLS0tIHU1R2tWQ0FSZG1KSUlOa0F3Z3Vm
            dHZ3NTB5QWpvZWtMVmpvMWVFVkhjYkUKpqc7xLY89B0tQqKUW9/RKl7AKQIkdbf+
            aT3izDbeeYuTPhTWuEbnO/fSI7LvLQge/K1fQ442JELor/slGVDQJw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1yltgwsnfxgstlyhf2ek9kcug0f6hw9dkhkang9kcdr77qgj8ay4qg6p3yy
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBVHZBeGIxRVJYRllOMkJx
            b2Q4K0V4Z052Q0wyQ3VUYW9TS096UUxMcG5ZCjVJd3JCUWhXclRKZjc4Y3pJTDY5
            Ri9UeWxxQjZmWmcveHZ6L1hwVUo1cEUKLS0tIDZPV0tqYUJKaHFrY3pkb1pLaUJM
            WkhKWFNMU2RyQldKZ0ZEMi8rbTBqR3cKjycoJX9LCLM4bbsb6EjoBBUp5V/2NQCf
            pgI80P1baBLuizNguUWQm4EP8eAEPaEdoPt6KHejDNcvEB3tVV6erQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1983r92uvhyfsud6nvn5pjnv7jvkxx3wsfhu68j32ll8uqpnwmass90k80w
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-18T20:37:01Z"
    mac: ENC[AES256_GCM,data:pt4mnH8YFcSayDCYvJAtWhJ0u3B/zP+x6sOFKH55KDRPwaxKXhqT7fq/gcH9VBC6xpVGuSVkPF+EQJkJjVoI2ur7Du/tSVKCdwk7ZPkA6P/ShkM9AODSlGwqK1/lgS+CsNDqxh2cGLcpts2f10HLzhwYLc8GvUBqvjckC9vo698=,iv:Yrw0XAA88jLTVfWH4IkFPuLxedTkB1V7lNamI7A4ED8=,tag:/A+epAm/TS6h++ulF3G5JA==,type:str]
    version: 3.13.1
