apiVersion: v1
kind: Secret
metadata:
    name: litellm-values
    namespace: litellm
stringData:
    values.yaml: ENC[AES256_GCM,data:uikxWZg6PlHVbNcY3fzuOzTbdFE4ltHQ6wUbIKCbjzlEB1YFZZ3AbfXE+pok8SZ4CPfQEDMH2q/hPxfsrWZZMPS0DVtnHLh3mETyjsdgF/zQzvw812qgQ9V2PZu4LchualO+fUpXeihIJYFiRioeHoA4zMaP4Jq8bZhQQV94tH6Y7UZrO99KwrRlls5yKesHtbXq6ZlzRE2+RTIlYGqRBevOK6f9YMWASyioMZqnSXvwWdQJ3+D2DoNWds9YDt3ZJ5qXE2Y5eSMrjZXX+g/uRp0PsSsxnUJbr1PucDbpujK6C1ROMpYqi+OJOgHhMYauB/EzGeWkvPOoa7lTClW7IT7tXzkpEtGaixjP8x77rO386KNnMLLVvfpYsiFb0Mwuqrvc4SgomclASqQqmtX0Wbfr1cbW9Ot5ZnhAAX25WEtCBmY4VHWWrtoaHHaM28GWWcTI80fVSpHUXO1IQu6SnHG2VMJNIcnrOJl0nWQ9S5AJHhQRir82ihiKoPya93ctpepU7NKp2KnxOVLuMS2eyQcVL0G6qT4fUKA7dgNDlUVQ8UcO9moN1eSfEFpA9bzko+6OqYIu3G1m18bEOyUkO27rtRoRFre9GxaGMh+tXhpw/I34uJHo/WDMor3qUJtneDN6URUBY/kY+WQA+F1w0rULp2lE2e17BGG5UgCT9CeigvdQoaYwXbU9n2avfAIPkdBSsHydzlWrPpCTNE4g48y9HLJrz8+j9fs2In13wLRAUhGlCaRgSnA=,iv:Th/A6aqmZ6IuTrrNgvKpJ4CeQV7Eh8WVkk0d7riz4xQ=,tag:V9dpSq9cdeagDGSR60A6yA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAyYXdyL2dIeVIrNUxUZlpC
            cnNDVVdjMEp0eTI3WDJTSjVPa2N6NEkzd1VzCjZaUFhtaVpvL25pbWlMeWM2UVlp
            WGNpcVR6SUxWNkNzeFJBZ3l3SUxjRncKLS0tIGF3MHJmTUxRbGtLMGxZajFiNmha
            WE84bDJ1alZBV3JQQ3A1K05KUC90emcK1B38vCvG4z73ZE2cU119NHagzjFVs+Po
            b00X7YUDOcACZfFFrLAuZsm4VLL42zJzG22o6tuAjPFA37yV0Emsuw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1yltgwsnfxgstlyhf2ek9kcug0f6hw9dkhkang9kcdr77qgj8ay4qg6p3yy
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXZVlkQUp3UVdWQW1ybUw2
            V1dmMFdPTGMrNmtxdUVGRExYY0Z3UW5RYUM4CjhucHM0TkpWOUZ4dEIrSCs5S3dJ
            ZFVFRklsVHFkRDZzR2lSYzErdTlSaEUKLS0tIDRJMUREcTFYWHVobHJEcWFlbzZM
            WUwreEdVU3R5L1JraDRXamg0YU1zZXMKkPjsJqkAF/RGkBnqPDra/cm+kIsKo4G9
            9moUR/g7m5K96aB4QNrhc2GjJuzr/qGuhwykuO4tPeho5ZjRqZDCzw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1983r92uvhyfsud6nvn5pjnv7jvkxx3wsfhu68j32ll8uqpnwmass90k80w
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-08T10:00:59Z"
    mac: ENC[AES256_GCM,data:bSW1dSeJ6Q3/2iy7S9e7YvMcdP7rAfuBPQ7a+QeECEs+VPHb53eb3KqmxO8VbM1dxvRfnrI7HhVI0xmT4joc50XxkKRmvxzUslCbM7W01AlzBAUiAflVr9QrM98D/ckSBzutzQmThpl15EtAyYx0vh6n6w6lMOnIKUMHl54z9Gg=,iv:psI0LMhyEjUcEo8dbQhpasKUucZ0+2Bv4YULsBEQDwg=,tag:PO5GFwhWSlLx17NAR5jzHw==,type:str]
    version: 3.13.1
