---
# https://docs.litellm.ai/docs/proxy/deploy#helm-chart
# https://github.com/BerriAI/litellm/tree/litellm_internal_staging/deploy/charts/litellm-helm
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: litellm
  namespace: litellm
spec:
  type: oci
  interval: 1h
  # chart is ghcr.io/berriai/litellm-helm
  url: oci://ghcr.io/berriai
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: litellm
  namespace: litellm
spec:
  interval: 15m
  # timeout: 15m
  chart:
    spec:
      # helm show chart oci://ghcr.io/berriai/litellm-helm
      chart: litellm-helm
      version: "1.89.2"
      sourceRef:
        kind: HelmRepository
        name: litellm
        namespace: litellm
  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  valuesFrom:
  - kind: Secret
    name: litellm-values
  values:
    replicaCount: 1
    logLevel: DEBUG
    proxy_config:
      model_list:
      - model_name: gpt-oss-20b
        litellm_params:
          model: openai/gpt-oss-20b
          api_base: http://vllm-stack-router-service.vllm-stack.svc.cluster.local:80/v1
          api_key: dummy-not-used
          # arbitrary for self-hosted; for usage tracking
          input_cost_per_token: 0.0000002 # $0.20 per 1M input tokens
          output_cost_per_token: 0.0000004 # $0.40 per 1M output tokens
      litellm_settings:
        drop_params: true
      general_settings:
        master_key: os.environ/PROXY_MASTER_KEY
    db:
      deployStandalone: true
      useExisting: false
    # Config for bitnami postgres chart
    postgresql:
      image:
        repository: bitnamilegacy/postgresql
      architecture: standalone
      auth:
        username: litellm
        database: litellm
      primary:
        persistence:
          enabled: true
          size: 5Gi
          storageClass: local-path
        resources:
          requests:
            cpu: 100m
            memory: 256Mi
          limits:
            memory: 512Mi
    # LiteLLM proxy resources
    resources:
      requests:
        cpu: 100m
        memory: 256Mi
      limits:
        memory: 2Gi
    # keep ClusterIP, we'll add Ingress separately
    service:
      type: ClusterIP
      port: 4000
    ingress:
      enabled: true
      # host is defined in config.enc.yaml
      className: "traefik"
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt-prod
    migrationJob:
      enabled: true
      hooks:
        argocd:
          enabled: false
        helm:
          enabled: true
    serviceMonitor:
      enabled: false
