---
# https://docs.litellm.ai/docs/proxy/deploy#helm-chart
# https://github.com/BerriAI/litellm/tree/litellm_internal_staging/deploy/charts/litellm-helm
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: litellm
  namespace: litellm
spec:
  type: oci
  interval: 1h
  # chart is ghcr.io/berriai/litellm-helm
  url: oci://ghcr.io/berriai
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: litellm
  namespace: litellm
spec:
  interval: 15m
  # timeout: 15m
  chart:
    spec:
      # helm show chart oci://ghcr.io/berriai/litellm-helm
      chart: litellm-helm
      version: "1.90.0"
      sourceRef:
        kind: HelmRepository
        name: litellm
        namespace: litellm
  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  valuesFrom:
  - kind: Secret
    name: litellm-values
  values:
    replicaCount: 1
    logLevel: DEBUG
    # https://docs.litellm.ai/docs/proxy/config_settings
    proxy_config:
      model_list:
      # - model_name: gpt-oss-20b
      #   litellm_params:
      #     model: openai/gpt-oss-20b
      #     api_base: http://vllm-stack-router-service.vllm-stack.svc.cluster.local:80/v1
      #     api_key: dummy-not-used
      #     reasoning_effort: "high"
      #     # arbitrary for self-hosted; for usage tracking
      #     input_cost_per_token: 0.0000002 # $0.20 per 1M input tokens
      #     output_cost_per_token: 0.0000004 # $0.40 per 1M output tokens
      # - model_name: qwen36-27b-awq
      #   litellm_params:
      #     model: openai/qwen36-27b-awq
      #     api_base: http://vllm-stack-router-service.vllm-stack.svc.cluster.local:80/v1
      #     api_key: dummy-not-used
      #     reasoning_effort: "high"
      #     # arbitrary for self-hosted; for usage tracking
      #     input_cost_per_token: 0.0000002 # $0.20 per 1M input tokens
      #     output_cost_per_token: 0.0000004 # $0.40 per 1M output tokens
      # - model_name: devstral-small-2-24b
      - model_name: devstral-small-2-24b-awq-4bit
        litellm_params:
          # model: openai/devstral-small-2-24b
          model: openai/devstral-small-2-24b-awq-4bit
          api_base: http://vllm-stack-router-service.vllm-stack.svc.cluster.local:80/v1
          api_key: dummy-not-used
          reasoning_effort: "high"
          # arbitrary for self-hosted; for usage tracking
          input_cost_per_token: 0.0000002 # $0.20 per 1M input tokens
          output_cost_per_token: 0.0000004 # $0.40 per 1M output tokens
      litellm_settings:
        drop_params: true
        # https://docs.litellm.ai/docs/proxy/prometheus
        callbacks:
        - prometheus
        require_auth_for_metrics_endpoint: false
        # If true, routes OpenAI /v1/messages requests through chat/completions instead of the Responses API.
        # Response API with Streaming doesn't support Function Calling (wip),
        # see https://docs.vllm.ai/projects/recipes/en/latest/OpenAI/GPT-OSS.html#harmony-format-support
        use_chat_completions_url_for_anthropic_messages: true
      general_settings:
        master_key: os.environ/PROXY_MASTER_KEY
    db:
      deployStandalone: true
      useExisting: false
    # Config for bitnami postgres chart
    postgresql:
      image:
        repository: bitnamilegacy/postgresql
      architecture: standalone
      auth:
        username: litellm
        database: litellm
      primary:
        persistence:
          enabled: true
          size: 5Gi
          storageClass: local-path
        resources:
          requests:
            cpu: 100m
            memory: 256Mi
          limits:
            memory: 512Mi
      metrics:
        enabled: true
        image:
          repository: bitnamilegacy/postgres-exporter
        serviceMonitor:
          enabled: true
    # LiteLLM proxy resources
    resources:
      requests:
        cpu: 100m
        memory: 256Mi
      limits:
        memory: 2Gi
    # keep ClusterIP, we'll add Ingress separately
    service:
      type: ClusterIP
      port: 4000
    ingress:
      enabled: true
      # host is defined in config.enc.yaml
      className: "traefik"
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt-prod
    migrationJob:
      enabled: true
      hooks:
        argocd:
          enabled: false
        helm:
          enabled: true
    serviceMonitor:
      enabled: true
