---
test: ENC[AES256_GCM,data:qdL9Cw==,iv:5La3v4iatYFEMPyobghKAo4Jr/dxJyL5CsI9AnaBizA=,tag:7meSwvrUmSTKYKRe2i+78A==,type:str]
another: ENC[AES256_GCM,data:bqnQMw==,iv:aAYjUnfNSXJawA9oSKxdy94yPS658kOgbMiDXg5poyM=,tag:mWRzHxPBmh0u11ShU+LiTA==,type:str]
sops:
  age:
  - enc: |
      -----BEGIN AGE ENCRYPTED FILE-----
      YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB0V3dtMjJMYTg4RFdmMFRZ
      UDE4ZFJxMmdock5aQlFENW8rNTlQb1A1YWlnCnAyVE1EeVZ1QWdDUEdwdloxWmFC
      WkM0MHN3em0ycHdJdUhzRlJIck5IOUEKLS0tIDduMFlhRDBvSDBSUXZqVG1ldnh0
      VC9oZ1Q1Uk9Pb1BDeVZSMk50OWNHbHcKC7n5cIFzRZ2NB3ivf/57bY2vz3CSrbXj
      5hs4a9uIs/RsaYFCNyjbHzTzdGixEE8pDOuRAjZ5JEAFdTdbzYcpTw==
      -----END AGE ENCRYPTED FILE-----
    recipient: age1yltgwsnfxgstlyhf2ek9kcug0f6hw9dkhkang9kcdr77qgj8ay4qg6p3yy
  lastmodified: "2026-06-16T12:49:40Z"
  mac: ENC[AES256_GCM,data:DZ/Dk0SuD1JoR45EKc5btxl+cdR3QjF4RbAdQ0C0MZEDX1MlyxDZBDsrLzNpYol18jieXTes95wPVj78Z3Fj7sBA/gTY+TyFPBUAZKiy1OCa1JrcWj1Xf/I63kO2QevyMWKOnSkFdZkRWq/xE8YV0/lvU+hdcz/Zc5sGo0/h0bU=,iv:RMpSZ5FHxn9h7vF6XPjLVgcY8KKq1F6/JKtP5u2Lomo=,tag:KbPecOQLaGXUy99muTHLmw==,type:str]
  unencrypted_suffix: _unencrypted
  version: 3.13.1
