apiVersion: v1
kind: Secret
metadata:
    name: kagent-openai
    namespace: kagent
stringData:
    #ENC[AES256_GCM,data:PXTne9vdsI2f1CV6c0r6ETLXLIHErBAKzQPqBi7cRY7bbo9XwZ9dzLbrk2JUKpQaK7QXzVCGeig78iApyTFUryWJ6Cgjh5TbRA==,iv:rSyF4PF1I7qu3SQlCVL2zseAsg1hEXcTS03mv+uTeHo=,tag:fZ+CuQjBFvll/CO5eDuq9Q==,type:comment]
    OPENAI_API_KEY: ENC[AES256_GCM,data:GlyKPrRgj4mHa7q+S9l0p4NzcHHSFPfdB3a7DWBGGkp4ZMJC9x4=,iv:0E78mnMiMOwLZTPN58egFmouH5wW8lqPZrAFbr2DEYY=,tag:DO0esSCkvukSwALT7PrXWw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSArM1d1VGxDK2gybDQzZWY5
            dC9xVmJ6VFlibmxJRjlsdll4MXdLc3R4dVZrClRQS2R5MjNUVyt3aGhKNzBqQklj
            M2dKQms2U08wU1Mra2s5ak9rUFpCeW8KLS0tIGFOdVgrd0FQZFlMRGdxWXlZTUVz
            cjdqUTFVUFpoYlpGT0pweVVGQUdrdFkKpCxorf/gk2FG0kkyryMtQaQz5ciHrJlk
            fSL3V7emVux7B8l5h/4Qg1q8h87sFmn8fGrsKrlysp7ICUhR6z+g+A==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1yltgwsnfxgstlyhf2ek9kcug0f6hw9dkhkang9kcdr77qgj8ay4qg6p3yy
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmMDB5S3lwai9tT1dHKzFO
            dmJMMkJudFBTWDNzSXNYcXpPYVIyYUpCREZNCmJqUnV2QWpKQ2RMUjBoSnlqc0Vu
            bGtEOVhObDVhV0VBbzBFZ3ZRV0hFSGsKLS0tIDF5M0dzcnVpRldRQkxXQmE1YXZC
            RTg1Z2l6QU9TUWUvamp0OUtaa2ZCZjAKQJH7/RnhxjkUiHunKOBc5bzARo8c8XdH
            /GVJjD9yc43MfMFyiY9rPCl/cJMrmrvd5vmGrvI/mDs/FAhBjZT4/Q==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1983r92uvhyfsud6nvn5pjnv7jvkxx3wsfhu68j32ll8uqpnwmass90k80w
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-06T14:46:44Z"
    mac: ENC[AES256_GCM,data:BrNNt8rdd8hXu+OzYow4VHRWyIS4Eb/p3Kldt0YLBIQOVg5iXEy8EOtqONRrypqlrVQnmNEDBexl17KQfuEcmv6SRA4tFe+DK82IYMvUoc0u7V5Lf6RuptnW4xt4gaoJhJVJbL+Vc2fR0DFGXEq4aPTe22R3+QYU2TBdKf8pwq4=,iv:qvofg0LKvprYucIbofHVciRA8JqACRGKTY089TMWxrk=,tag:4BOEmMsW8ab+skyjZONGdA==,type:str]
    version: 3.13.1
