apiVersion: v1
kind: Secret
metadata:
    name: kagent-values
    namespace: kagent
stringData:
    values.yaml: ENC[AES256_GCM,data:kvdwXy50C9gbYVikTDoRZSMcVPu1yp68K2TqGNG7i1ODfaRWOrKR05RT4PaiySoKp5vRBDkDGOxgw8FAXutnvjbH4xRMwc6DybL0HVn1tMN0A/NE9KIt6HuGc2LvuV/4yS/vSAHyx+Yz1eVDNhk2m88gWP4u7kdqkhZYkjaYlV3YNmV8JDfFWQsLJUPbcHQhhmn4XZYXie9N3qi44Q==,iv:2EimowtyT3Q5bAi3vSHpMln7p/FW9gJ6dU3HgNqe0NQ=,tag:iTTDqMqPXAsKDGEhwQRG3w==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA0UVJiUUNkdFVDVzlXZ2dx
            eGFRUVlNSTlYT2FHb0VuWllhQytPUmpQcEFBCmkvdVZBTU9FYWtVNmhjM3lIRktl
            aUxTdUZXWkZ5ajhkZlM3bDlBYVQydmMKLS0tIFpxYmgwbFFrZFRjTXhGQWgzNkti
            TTBHVjR5d1RFek9PenNuaWkwSHZsNW8KRzsvug5yef9Ka3iK7ES7eqxD0YtIGocQ
            hGUxd1h4DPPDlrmkVBGUYhe9dewo1Do72xOz2bZ94zmGDj6pcY8QiA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1yltgwsnfxgstlyhf2ek9kcug0f6hw9dkhkang9kcdr77qgj8ay4qg6p3yy
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBHUVFKaE54Wi9aWlVKc1Js
            ZzJhVVoxU1B3OWNGQ2pNdkhLSVVhY0ZrU1FZCjZRaU5xMFZjbmlPa0NMRTVaM2lG
            UGJkTDhURnB1aUpnLzg5REhzK2ZKc1EKLS0tIEJqOTFkRFlNMTlqVitGZnUzSEhL
            M09JVFVVNDdIYkdsenkwWHlGYmNwMWsKzQa1sDNfl9fbhYaJ/uqICtmRApl5wbWJ
            V0HbHS60BL16MtHrX1WnhQe8i570Y7wQb6s/NgIR/V3CKnKLK6Gh7A==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1983r92uvhyfsud6nvn5pjnv7jvkxx3wsfhu68j32ll8uqpnwmass90k80w
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-30T10:33:27Z"
    mac: ENC[AES256_GCM,data:4Fa5p3rQexSvWuYrcGLzBa/tjonoffGByEFxnHgKYj7Lv587x6dUKV/9KU2FHoewBdMqFqjagrCRsqaSvmocJwIglPr+TczANxNIHPX4m41zvBFPuF2hkmc0PCZWA7xZeYYHwJGUrmE+D6DCfB3G/ktC8BDiafb0LoNOWhp0ufg=,iv:/7OvyixQFHwcoQg2iQ8M3tne/N46OZgPJ6ScLJ+jpNw=,tag:8OVbxJoNX2BIJeIszhr5ng==,type:str]
    version: 3.13.1
