apiVersion: v1
kind: Secret
metadata:
    name: kagent-values
    namespace: kagent
stringData:
    values.yaml: ENC[AES256_GCM,data:7OfdG2B//R0tcYr6vN0eyLEIymnR3G+Nu7qSq9av6gTNzM+fGW+fqbDvHuiKGJ+8QYGhgkd7BpavY9oJuyQjoyw2GWq9qFtasR9xVz/GtwF/ykY5E/Ovk1OVzZP6GADQZuQ+NQ0c98du5O3qfpRT,iv:UCd8m5I2slCD0KxPhoRCjOXzBi3MpRNMn1y4i19+9zQ=,tag:oKZYAea5Qj2j6djQ4g0Zfw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA0UVJiUUNkdFVDVzlXZ2dx
            eGFRUVlNSTlYT2FHb0VuWllhQytPUmpQcEFBCmkvdVZBTU9FYWtVNmhjM3lIRktl
            aUxTdUZXWkZ5ajhkZlM3bDlBYVQydmMKLS0tIFpxYmgwbFFrZFRjTXhGQWgzNkti
            TTBHVjR5d1RFek9PenNuaWkwSHZsNW8KRzsvug5yef9Ka3iK7ES7eqxD0YtIGocQ
            hGUxd1h4DPPDlrmkVBGUYhe9dewo1Do72xOz2bZ94zmGDj6pcY8QiA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1yltgwsnfxgstlyhf2ek9kcug0f6hw9dkhkang9kcdr77qgj8ay4qg6p3yy
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBHUVFKaE54Wi9aWlVKc1Js
            ZzJhVVoxU1B3OWNGQ2pNdkhLSVVhY0ZrU1FZCjZRaU5xMFZjbmlPa0NMRTVaM2lG
            UGJkTDhURnB1aUpnLzg5REhzK2ZKc1EKLS0tIEJqOTFkRFlNMTlqVitGZnUzSEhL
            M09JVFVVNDdIYkdsenkwWHlGYmNwMWsKzQa1sDNfl9fbhYaJ/uqICtmRApl5wbWJ
            V0HbHS60BL16MtHrX1WnhQe8i570Y7wQb6s/NgIR/V3CKnKLK6Gh7A==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1983r92uvhyfsud6nvn5pjnv7jvkxx3wsfhu68j32ll8uqpnwmass90k80w
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-30T10:48:39Z"
    mac: ENC[AES256_GCM,data:RfSaCezKCvespxLYWbprG0Vvv+/0ebh19L5dV+h/vPzHbFUPakBmKEr4MsNHuK5/oICHxx6jeeaOfg80L1lTG5HoTPRV/4cG01wSO3jdbrKWpHrzzDDMWg562qHURdAB9z2+kMOvsIrmVApL0VnJglYxZb5cpg1pIz1h0FaDNbA=,iv:vM+KuBFMEB6/5TMy0QRy9yIufzFkWrbKH90v0fvnVz0=,tag:wFKPwBez+XN5ImIts2lS7w==,type:str]
    version: 3.13.1
