apiVersion: v1
stringData:
    #ENC[AES256_GCM,data:CMB7cPw2gD9AnpWheonktrLwM882gK5Mjbm46XwCGXRKYASRzjYGpceLk3UmTBHy1w6wDLE=,iv:XgGHliSOQc36nVMMSmotUYO31o+25TDipDrR98dFvLI=,tag:IurwgKsnIBUvhauTocLdgg==,type:comment]
    token: ENC[AES256_GCM,data:r5Wid+j2IxqVGYzSLmJuJCDyyXkFPyWMY24n/S7Go7QngUS1mg==,iv:7Y76b7WT1Ahxk6+EpWUNbpku444DFpZMUAnvjb/Oux8=,tag:pXHFBHM/kSbtThcYfd4fKA==,type:str]
kind: Secret
metadata:
    name: hf-token
    namespace: vllm
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA4c1R0ZlZjVzVxQms5c056
            Z29BK1hCVTBtVGNwV3ZMU3k4bUoyRVIzNjNzCnhqSVdXNU9mSUFBU3YyY2s1bWZm
            ZEVwQnE5cW9Ua21MdG1pZTVuMHJXeE0KLS0tIHd6UklXMFhRQU0wQk5SRTFaOGR4
            b3NlOGdVbDZKbjhQYmJYVjlhc1lqa2MKuENDL+LC7PEVfQ1xd1+QiwKC+zweqZRQ
            Ofa5iqh60MSq2arElf8EChCUvDHyPb6Nw/WHXxgoOvD5jx7PfE42Lg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1yltgwsnfxgstlyhf2ek9kcug0f6hw9dkhkang9kcdr77qgj8ay4qg6p3yy
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBnVWQvUVlvYXg4alE3bytT
            MWdQeTlwUEVQbU0wMDB1SHlDUndDZjNLZkUwCjdnN3VieXFxdWhrNjVSZlB5U3dX
            TnZhZXBXV1NISWpYa1dLbVVHQnc2TEEKLS0tIFlYeHdzU01Da2RUOUFHZ0hSZnBV
            VGRHanZLbjJRSHF0STNPN29yWHU4NXMKAK6aQToNb4+ykQxKkUTwEEf9EUxEKzJQ
            WpdfGWmpa/Jdu1UIzNkY17mXCYUx1/aPKK3IDkOOzXAASPDhLvdrIA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1wfk6k9ls7tu70newlv8sp9z0veu7jl5tr83pcw507ushwj3s43kswev88r
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-16T16:47:55Z"
    mac: ENC[AES256_GCM,data:f5jdRvcFx9dtiOrv5E3/JsOFQx7EOc+R9++8obQ26LNIS+9x2HHNF/8IE/TL+XppGFmmM64e9/ZGqnxBnDJuKMURLNEJ5fVkx/+Hd1Er7iF1mRDUyaGPGzmWeW2Z3EOKJwmqKENhVOTph/NS3eMye4xSuq4SJorQ37JU/c2Hi8I=,iv:rieGx2KOcwYu84nzK0V7xSzEF0GDF4HQtQRkceSJE/M=,tag:29PtmPMIgbm21BDMf+qXKA==,type:str]
    version: 3.13.1
