apiVersion: v1
kind: Secret
metadata:
    name: kube-prometheus-stack-values
    namespace: kube-prometheus-stack
stringData:
    values.yaml: ENC[AES256_GCM,data:5YRc7hiTLfxtSZahBrwfcXo/YSfwI1mvH1AdFlkl4UaVvFgjK4WD7Tcz7Wc+lUl4yQ==,iv:gSE/E8M47N6g8vFlNkOVdevTLlpj3d5QJb18/NIC2/g=,tag:RU16pfuJDdz+QnxaTwD+5Q==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBoSzRNY0IzYzJtK2Q2elMv
            bXo5Rlhpei9PdlBJdndqU1BZNTZvU0EvWm5NCnBneVY5WjEzeGNqM2c2NnRia3kx
            SlJ5UHJNR2pOTWZJSlp1OEo5RTVqK0UKLS0tIFJGTG9CVlZZU3BocTlyUXJwbzBX
            Q3dnNVBhT2g4QUJJT1d2ZGVRNFRBMlUK8ZAFwqbcja9OVLl4A0ITwRK2c6TIjZLo
            x4cwrCtLWAc6q7Y+JxfoZR41Geu/d0//y+jbsylesQL5ZhyI4LwQHg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1yltgwsnfxgstlyhf2ek9kcug0f6hw9dkhkang9kcdr77qgj8ay4qg6p3yy
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBHejN1YnhQUzE0emNlQkg1
            b2Q4WXZDK09qdXVQY0JDZmRWMWp2S3RkcXlBCnN6cndGVDB3NWREcmpYc3FjTmIx
            Q1dqMFRya1NQV3V2S3RIem1KQ2tXdzgKLS0tIEIzTkhScTBjVXZ4cUNzUStKS0F2
            UGpSZUlxOFlsa0tzcjhWRXhla1NKWE0KVw+/mO0OZB3hfyCCr3+hLz4k6HzRqeG1
            rKg/2pQSqtsIw9MvCLzAZ6XvaGS9FyqLgZyGHbkKgmvJQuEBUoP8Dg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1983r92uvhyfsud6nvn5pjnv7jvkxx3wsfhu68j32ll8uqpnwmass90k80w
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYd3pSR0k2TDZvblBISEsy
            V0RwQm9IdWFYVW5QZGtiNU9RTmN4dUJNRmtBClA5NjBWcUVPMjN3czcxRFl2dktK
            cTVsK011eFhSWkkwbStJSkxBZnAxdVEKLS0tIDlwUVhpUEdBQ2RzZTh6OFJnbHVz
            NVNHVzFNZlZmS0pkclhjb0RoT2ZsaHcKLAO9MKhNUrIPp+1iGTzHoE8jslDujuya
            ZCUb47Rpsjr/3k4ObVo8GyeLPaWFVWrwm6fXtZlWzBYUROaMANmjlg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1zmxxfmfawpushkt3juhu2eu0x8le3u385c623xjxn930ttqexc6sjcfhuz
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-10T14:59:17Z"
    mac: ENC[AES256_GCM,data:nLJfmCcpuSGcgbdROmA06weC1o3ZiHOYNdtPnTQwkvoWALJMakdfDKD0ZGxi9YsQDuLEB6ZnxLtrPbvwEcQmCJr87iotKTZm97AHFaiJxooM6v9urMgGNlaqQzYmMIvSNBB+x6OydrCo46jn5zm/uWn1rMyPMD0ohS2AutxjYo4=,iv:DOPiy9mESbzH5NnCT1V3facK0mU4zPUCnHrgapo50EU=,tag:WvBq/OA11IxSoZPDzeM5xQ==,type:str]
    version: 3.13.1
